export const ConsoleView = () => {
  return (
    <div className="max-h-full overflow-scroll">
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
      <div>Console view</div>
    </div>
  );
};
